### PR TITLE
fix: initial hostname

### PR DESCRIPTION
**Pull request by endorfin**
Fix for the error:

**Embedly::BadResponseException (Bad Response : #<Net::HTTPMovedPermanently 301 Moved Permanently readbody=true>**

### CODE REVIEW

**Comment by k-rudy** [comment]
@stiteler @whichlight could you please take a look at this ASAP. Embedly API is no longer usable without either this fix or bringing back the old API url (preferable).

**Comment by jdcalvin** [comment]
Hi. This fix does not appear to work. The host `https://api.embedly/` is non responsive. I can make direct api calls with the url generated by this gem, but the gem itself is what generates the 301 for me. The Faraday, Net::HTTP, and Typhoeous adapters all return 301 for a valid url.

Modifying my configuration with the following fixes the issue for me.
```
Embedly.configuration.add_requester(:httparty) {|_| HTTParty }
Embedly.configure { |config| config.request_with :httparty }
```

**Comment by endorfin** [comment]
@jdcalvin the problem is defined HTTP host (http://api.embed.ly) which will redirected to HTTPS. 

Whether now https://api.embed.ly is used as default or https://api.embedly.com as it is also written in the documentation, must be decided by @stiteler or @whichlight 

Temporarily it can be easily fixed by specifying the hostname when initializing the API. It is not necessary to configure another requester like httparty
```
embedly_api = Embedly::API.new(
  key: YOUR_API_KEY,
  hostname: 'https://api.embedly.com'
)
```

**Comment by sdhull** [comment]
If you `curl -v https://api.embedly.com` (new hostname in this PR), it redirects to `http://embed.ly` and if you `curl` _that_, it redirects to `https://embed.ly`

And the gem hasn't configured the various http requesters to follow redirects, afaict

**Comment by endorfin** [comment]
> If you `curl -v https://api.embedly.com` (new hostname in this PR), it redirects to `http://embed.ly` and if you `curl` _that_, it redirects to `https://embed.ly`
> 
> And the gem hasn't configured the various http requesters to follow redirects, afaict

The redirection happens only for https://api.embedly.com not for the api urls like https://api.embedly.com/1/extract

**Review by stiteler — APPROVED** [review]

**Pull request merged**
